Login, Register, Global user provider
melosync/web-app pull request #5
Opened 2019-10-28 16:15 UTC by pierresaid

2019-10-28 22:25 UTC, benard-g requested changes
Bon pas mal de com' ^^

2019-10-28 22:25 UTC, benard-g commented on .env
> +BROWSER=none
👍 Mets le retour à la ligne par contre

2019-10-28 22:25 UTC, benard-g commented on .eslintrc.json
> +    ],
Tout ça je vais pas vérifier, je te fais confiance

2019-10-28 22:25 UTC, benard-g commented on src/App.tsx
> +import UserProvider from "./store/user";
Je proposerais plutot de faire des groupes distints pour les imports de sous dossiers et ceux du dossier courrant.
Typiquement ici:
```ts
import Navbar from "./components/Navbar";
import Home from "./pages/Home";
import Login from "./pages/Login";
import Register from "./pages/Register";
import UserProvider from "./store/user";

import theme from "./theme";
```

2019-10-28 22:25 UTC, benard-g commented on src/index.scss
> +@import "~normalize.css";
Ca fait quoi le `~` ?

2019-10-28 22:25 UTC, benard-g commented on src/index.scss
> +}
Ca je prefererais le voir dans le dossier de `App`. `index.scss` c'est des styles globaux.

- App.tsx
- App.style.scss
- App.test.ts(x)
(et si tu es dans un dossier de composant, tu aurais en plus un `index.ts` qui export le `Component`

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/AddUrlDialog/index.tsx
> +import getIdFromUrl from "../../../helpers/getIdFromUrl";
Faut harmoniser le style d'import, je crois que `airbnb` requiert l'`export default`
```ts
import MusicItem from "...";
```

2019-10-28 22:25 UTC, benard-g commented on src/helpers/getIdFromUrl.ts
> +}
C'est l'id de la video ?
Je recommanderais de faire une classe plus explicite `YoutubeHelper` ou dans le genre.

2019-10-28 22:25 UTC, benard-g commented on src/components/Navbar/index.tsx
> +import { Button, Menu, MenuItem } from "@material-ui/core";
import 1 par 1 comme au dessus

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/AddUrlDialog/index.tsx
> +    if (newUrl.length <= 0) return;
Pas de if en une ligne (toujours avec les accolades aussi) !
```ts
if (newUrl.length !== 0) {
    return;
}

const res = ...
```

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/AddUrlDialog/index.tsx
> +    if (res === null) return;
pareil

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/AddUrlDialog/index.tsx
> +      (youtubePlayer as any).loadVideoById(res);
`any` ? 😠

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/AddUrlDialog/index.tsx
> +  function AddUrlClicked(e: React.SyntheticEvent<any, Event>): void {
Perso je mets des arrow function partout. si tu peux faire de meme 🙂. Et les noms de variables/function en `camelCase`.

Aussi, il a pas un type mieux que `any` ton evenement ?

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/index.scss
> +}
retour a la ligne

2019-10-28 22:25 UTC, benard-g commented on src/pages/Login/index.tsx
> +import { Link } from "react-router-dom";
react-router-dom au dessus

2019-10-28 22:25 UTC, benard-g commented on src/store/createCtx.tsx
> +type Context<A> = readonly [
~`A`~ => `TData`, `T` a la limite

2019-10-28 22:25 UTC, benard-g commented on src/services/Api.ts
> +  baseURL: "http://localhost:5000/",
`.env.development` ou `.env.development.local` (je crois)

```
REACT_APP_API_URL="http/..."
```

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/AddUrlDialog/index.tsx
> +type AddUrlDialogProps = {
Juste Props ? vu que c'est scopé.

2019-10-28 22:25 UTC, benard-g commented on src/App.tsx
> +import { CssBaseline } from "@material-ui/core";
importe depuis `material-ui/core/CssBaseline`. (ca fait des imports plus leger).

2019-10-28 22:25 UTC, benard-g commented on src/App.tsx
> +              <Route path="/register" component={Register} />
Mets un fallback (redirect sur "/")

2019-10-28 22:25 UTC, benard-g commented on src/App.tsx
> +          <CssBaseline />
Du coup si y'a ça tu peux rm mon `reset.scss`

2019-10-28 22:25 UTC, benard-g commented on src/components/Navbar/index.tsx
> +      <AppBar position="sticky" className={styles.AppBar} color="inherit">
2 fois le style `Appbar` ?

2019-10-28 22:25 UTC, benard-g commented on src/components/Navbar/index.tsx
> +  const { state: user, update } = React.useContext(UserContext);
```
const { state: user, update: updateUser } = React.useContext(UserContext);
```

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/AddUrlDialog/index.tsx
> +  youtubePlayer: any;
`any` 😠

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/AddUrlDialog/index.tsx
> +      <DialogContent style={{ padding: "25px" }}>
pas de style `inline`

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/AddUrlDialog/index.tsx
> +      <Typography variant="h4" component="h4" style={{ margin: "20px" }}>
Pk un h4 ?

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/index.tsx
> +import "./index.scss";
melange pas les types d'imports

```
// system

// libs

// dossiers voisins

// meme dossier
```

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/index.tsx
> +  const [AddUrlDialogopen, setAddUrlDialogOpen] = useState(false);
addUserDialogOpen

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/index.tsx
> +  ]);
De biens belles chansons 🙂

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/index.tsx
> +      event.target.loadVideoById((next as any).id);
Et si tu ajoutes `id` a `MusicItem` on peut eviter le `any` non ? 🙂

2019-10-28 22:25 UTC, benard-g commented on src/pages/Home/index.tsx
> +    <Container style={{ width: "100%", marginTop: "30px", height: "60vh" }}>
inline styles :'(

2019-10-29 10:34 UTC, pierresaid commented on src/index.scss
> +@import "~normalize.css";
ça va chercher dans les node_modules

2019-10-29 10:41 UTC, pierresaid commented on src/pages/Home/AddUrlDialog/index.tsx
> +import getIdFromUrl from "../../../helpers/getIdFromUrl";
Pour les types c'est galère

2019-10-29 10:53 UTC, pierresaid commented on src/pages/Home/AddUrlDialog/index.tsx
> +      (youtubePlayer as any).loadVideoById(res);
J'ai pas de type pour la ref du player youtube

2019-10-29 11:22 UTC, pierresaid commented on src/pages/Home/AddUrlDialog/index.tsx
> +      <Typography variant="h4" component="h4" style={{ margin: "20px" }}>
Pour la font-size

2019-10-31 11:28 UTC, benard-g requested changes
Tres bien 👍,
Juste encore quelques com' sur la forme

2019-10-31 11:28 UTC, benard-g commented on .eslintrc.json
> +    "react/no-array-index-key": "off",
Euh tu es sur ?

2019-10-31 11:28 UTC, benard-g commented on src/App/App.test.tsx
> +import App from "./Index";
from "App" plutot, "index" c'est pour l'exterieur

2019-10-31 11:28 UTC, benard-g commented on src/App/Index.tsx
> +                <Redirect to="/" />
👍

2019-10-31 11:28 UTC, benard-g commented on src/App/Index.tsx
> +import React from "react";
Juste le nom du fichier :
~Index.tsx~ --> index.tsx

2019-10-31 11:28 UTC, benard-g commented on src/App/Index.tsx
> +import "./index.scss";
Import plutot en module pour que le css soit scopé

```ts
import Styles from "App.styles.module.scss"; // "styles" pas specialement necessaire vu qu'on a deja "module" ici
```

2019-10-31 11:28 UTC, benard-g commented on src/App/Index.tsx
> +    <div className="parent">
Avec le module, cela devient:
```tsx
<div className={Styles.parent} >
```

2019-10-31 11:28 UTC, benard-g commented on src/App/index.scss
> +.parent {
Comme dit plus haut, renomme le fichier `App.module.scss`

2019-10-31 11:28 UTC, benard-g commented on src/App/index.scss
> +.App {
Saut de ligne

2019-10-31 11:28 UTC, benard-g commented on src/components/Navbar/index.tsx
>  import { Link } from "react-router-dom";
index.ts devrait juste exporter Navbar from "./Navbar.tsx"

2019-10-31 11:28 UTC, benard-g commented on src/helpers/YoutubeHelper.ts
> +   */
👍

2019-10-31 11:28 UTC, benard-g commented on src/index.tsx
> +import App from "./App/Index";
from "./App"; un fois que tu auras renommé en "index.ts"

2019-10-31 11:28 UTC, benard-g commented on src/pages/Home/AddUrlDialog/index.tsx
> +type AddUrlDialogProps = {
Du coup pas juste `Props` ?

2019-10-31 11:28 UTC, benard-g commented on src/pages/Home/AddUrlDialog/index.tsx
> +      <DialogContent style={{ padding: "25px" }}>
Toujours contre le inline 😢. Tu peux pas assigner `className` ?
Si jamais tu peux pas, il me semble que les composant material-ui ont tous un attribut `classes` qui permet de mettre un objet. Donc a la limite faut une constante en haut du fichier `MY_SPECIAL_STYLE` que tu lui assignes ensuite.

2019-10-31 11:28 UTC, benard-g commented on src/pages/Home/index.tsx
> +  const [addUrlDialogopen, setAddUrlDialogOpen] = useState(false);
Open

2019-10-31 11:28 UTC, benard-g commented on src/pages/Home/index.tsx
> +  const [addUrlDialogopen, setAddUrlDialogOpen] = useState(false);
Installe cette extension vscode
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2019-10-31 11:28 UTC, benard-g commented on src/pages/Home/index.tsx
> +    <Container className="HomeContainer">
👍

2019-10-31 11:28 UTC, benard-g commented on src/pages/Home/index.tsx
> +        {playlist.map((m, idx) => (
`m` c'est quoi ? `music` ?

2019-10-31 12:50 UTC, pierresaid commented on src/App/App.test.tsx
> +import App from "./Index";
Non ça ne marche pas

2019-10-31 13:46 UTC, benard-g requested changes

2019-10-31 13:46 UTC, benard-g commented on src/pages/Home/index.tsx
> +      <div className="NextLabel">
Utilise du css scopé tout le temps stp (import Styles from "Xxx.module.scss")

2019-10-31 13:46 UTC, benard-g commented on src/pages/Register/index.tsx
> +          <h1 className="centered-text">Register</h1>
module css

2019-10-31 13:46 UTC, benard-g commented on src/pages/Register/index.tsx
> +            <div className="BottomFormContainer">
module

2019-10-31 13:46 UTC, benard-g commented on src/pages/Register/index.tsx
> +              {loading && <CircularProgress size={24} className="Loader" />}
Une const au dessus LOADING_CIRCLE_SIZE

2019-10-31 13:59 UTC, benard-g commented on src/App/App.test.tsx
> +import App from "./Index";
A priori tu as pas de fichier `App.tsx` donc normal

2019-10-31 14:11 UTC, benard-g approved these changes

2019-10-31 14:16 UTC, merged